### ISSUE TITLE
[Feature Request] Trigger CSV Download after approval

### ISSUE THREAD

**Issue by tertek** [BCCHR-IT/data-dictionary-revisions#1]
Our business requires that after an approval of Data Dictionary Changes there should be an automatic download of the Comparison of Changes (CSV file). Currently, this file can be downloaded only form the module page.

I have started local development and made first successful tests. Would you agree on such a new feature for the EM?
In that case I would submit a Pull Request.

Additional details regarding the feature can be shared/discussed after you give me green light.

**Comment by BCCHR-IT** [comment]
We'd be happy to incorporate a new feature, though I can't guarantee it would be done swiftly. What further details can you share?

**Comment by tertek** [comment]
>  I can't guarantee it would be done swiftly

Do you mean it could take long time to check the PR and merge it? In that case we would go for our own module, because we cannot wait all too long ;)

Further details:
- Module configuration option to enable/disable feature
- UI Switch in "Submit Changes" - modal to control configuration option (Ajax Request)
- Hook on "Submission automatically granted" and "Changes approved" to trigger Download of last two Revision Changes as CSV

**Comment by tertek** [comment]
![image](https://user-images.githubusercontent.com/75415872/126944703-ca955399-833c-40f2-8855-b6c9d174c36a.png)

![image](https://user-images.githubusercontent.com/75415872/126945483-388426c5-dd93-4632-9f37-beed7dacf206.png)

**Comment by BCCHR-IT** [comment]
You might be better off going for you own module for now, though you could also just use the changes you've made to the Custom Template Engine locally.

**Comment by tertek** [comment]
As you wish.
For me it is of course better to develop my own module, since I am more independent. By asking you I am just supporting the OSS principle.

"Local modules" as you say are not an option in the case that we do not have access to the server on file system level. Therefore we are dependent on "Official Modules" from the REDCap repository.
