### ISSUE TITLE
Inaccurate retrieval of column 'automatic' 

### ISSUE THREAD

**Issue by tertek** [BCCHR-IT/data-dictionary-revisions#2]
While retrieving all revisions with `getAllRevisions()`  there is an inaccurate SQL query when setting 'automatic' through string comparison:

        $sql = "select p.pr_id, p.ts_approved, p.ui_id_requester, p.ui_id_approver,
                    if(l.description = 'Approve production project modifications (automatic)',1,0) as automatic
                    from redcap_metadata_prod_revisions p left join redcap_log_event l
                    on p.project_id = l.project_id and p.ts_approved*1 = l.ts
                    where p.project_id = $pid and p.ts_approved is not null order by p.pr_id";

REDCap manages log events in multiple instances of table `redcap_log_event ` by adding indices at the end of table name. This leads to inaccurate results for the if condition which sets "automatic".

I would recommend, instead defining "automatic" by checking if  `ts_approved` equals `ts_req_approval`, since this should only for "automatic" be the case.

**Comment by BCCHR-IT** [comment]
Hello, sorry for the late reply. We've received recent news that this module will be incorporated into the REDCap core functionality in version 11.x, in the future, thus we don't foresee any further development happening. However we've pointed them to your concerns, to incorporate if they see fit. Thank you, for the recommendation.
